Audits/Models/Checklists/ChecklistExportCache.cs
using System;
using System.Collections.Generic;

namespace Audits.Models.Checklists
{
    internal static class ChecklistExportCache
    {
        private static readonly Dictionary<string, Record> _cache;

        static ChecklistExportCache()
        {
            _cache = new Dictionary<string, Record>();
        }

        public static byte[] Find(string checklistName)
        {
            lock (_cache)
            {
                Record record;
                if (!_cache.TryGetValue(checklistName, out record))
                {
                    return null;
                }

                var timeSpan = DateTime.Now - record.Timestamp;
                if (timeSpan.Minutes < 30)
                {
                    return record.Data;
                }

                _cache.Remove(checklistName);

                return null;
            }
        }

        public static void UpdateRecord(string checklistName, byte[] data)
        {
            lock (_cache)
            {
                InvalidateRecord(checklistName);

                _cache.Add(checklistName, new Record(data));
            }
        }

        public static void InvalidateRecord(string checklistName)
        {
            lock (_cache)
            {
                Record record;
                if (_cache.TryGetValue(checklistName, out record))
                {
                    _cache.Remove(checklistName);
                }
            }
        }

        private class Record
        {
            public Record(byte[] data)
            {
                Timestamp = DateTime.Now;
                Data = data;
            }

            public DateTime Timestamp { get; }
            public byte[] Data { get; }
        }
    }
}

Audits/Models/Checklists/ChecklistExportService.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using Audits.Models.Database_Manager;
using OfficeOpenXml;
using OfficeOpenXml.Drawing.Chart;
using OfficeOpenXml.Style;
using OfficeOpenXml.Style.XmlAccess;

namespace Audits.Models.Checklists
{
    public class ChecklistExportService
    {
        private const string Position = "Должность";
        private const string FullName = "ФИО";
        private const double SectionTableDefaulRowHeight = 24.9;
        private const double BottomTableRowHeight = 30;
        private readonly Checklist _checkList;
        private ExcelNamedStyleXml _checklistHeaderStyle;

        private ExcelNamedStyleXml _documentHeaderStyle;
        private ExcelNamedStyleXml _numbersTableStyle;
        private ExcelNamedStyleXml _parametersTableStyle;
        private ExcelNamedStyleXml _resposiblePersonsStyle;
        private ExcelNamedStyleXml _signsStyle;
        private ExcelNamedStyleXml _totalsSectionStyle;

        public ChecklistExportService(Checklist checkList)
        {
            _checkList = checkList;
        }

        public byte[] GenerateXlsxReport()
        {
            var data = ChecklistExportCache.Find(_checkList.Name);
            if (data != null)
            {
                return data;
            }

            var memoryStream = new MemoryStream();
            using (var package = new ExcelPackage(memoryStream))
            {
                // add a new worksheet to the empty workbook
                var worksheet =
                    package.Workbook.Worksheets.Add("Шаблон чек-листа - " + DateTime.Now.ToShortDateString());
                worksheet.DefaultRowHeight = 13.8;
                worksheet.DefaultColWidth = 9.109375;
                InitExcelStyles(worksheet);
                InitColumnsWidth(worksheet);

                var currentRow = 0;
                RenderContent(worksheet, ref currentRow);

                worksheet.PrinterSettings.FitToPage = true;
                package.Save();
            }

            data = memoryStream.ToArray();
            ChecklistExportCache.UpdateRecord(_checkList.Name, data);

            return data;
        }

        private void RenderContent(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            RenderHeader(excelWorksheet, ref currentRow);
            RenderMainTable(excelWorksheet, ref currentRow);
            RenderBottomTable(excelWorksheet, ref currentRow);
            RenderFooter(excelWorksheet, ref currentRow);
        }

        private void RenderMainTable(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            RenderMainTableHead(excelWorksheet, ref currentRow);
            RenderMainTableSections(excelWorksheet, ref currentRow);
            ++currentRow;
        }

        private void RenderFooter(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            currentRow++;
            excelWorksheet.Row(currentRow).Height = 20.1;
            excelWorksheet.Cells[$"A{currentRow}:D{currentRow}"].Merge = true;
            excelWorksheet.Cells[$"A{currentRow}:D{currentRow}"].Value = "Аудитор:";
            excelWorksheet.Cells[$"A{currentRow}:D{currentRow}"].StyleName = _resposiblePersonsStyle.Name;

            currentRow++;
            excelWorksheet.Row(currentRow).Height = 9.9;
            excelWorksheet.Cells[$"E{currentRow}:G{currentRow}"].Merge = true;
            excelWorksheet.Cells[$"E{currentRow}:G{currentRow}"].Value = Position;
            excelWorksheet.Cells[$"H{currentRow}"].Value = FullName;
            excelWorksheet.Cells[$"I{currentRow}:J{currentRow}"].Merge = true;
            excelWorksheet.Cells[$"I{currentRow}:J{currentRow}"].Value = "Подпись";
            excelWorksheet.Cells[$"E{currentRow}:J{currentRow}"].StyleName = _signsStyle.Name;

            excelWorksheet.Cells[$"A1:J{currentRow}"].Style.Font.Name = "Arial Narrow";
            excelWorksheet.Cells[$"A1:J{currentRow}"].Style.Font.Family = 2;
        }

        private void RenderBottomTable(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            RenderBottomTableHeader(excelWorksheet, ref currentRow);
            RenderBottomTableSections(excelWorksheet, ref currentRow);
            RendertRadarChart(excelWorksheet, currentRow + 1);
            RenderBottomTableFooter(excelWorksheet, ref currentRow);
        }

        private void RenderBottomTableFooter(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            currentRow++;
            InitBottomTableSectionStyle(excelWorksheet, ref currentRow);
            excelWorksheet.Row(currentRow).Height = BottomTableRowHeight;
            excelWorksheet.Cells[$"A{currentRow}:D{currentRow}"].Merge = true;
            excelWorksheet.Cells[$"A{currentRow}:D{currentRow}"].Value = "Средняя оценка по заводу";

            excelWorksheet.Cells[$"H{currentRow}"].Value = "Итоговая оценка";
            excelWorksheet.Cells[$"I{currentRow}:J{currentRow}"].Merge = true;
            excelWorksheet.Cells[$"G{currentRow}:J{currentRow}"].Style.Font.Size = 14;
            excelWorksheet.Cells[$"G{currentRow}:J{currentRow}"].Style.VerticalAlignment =
                ExcelVerticalAlignment.Center;
            excelWorksheet.Cells[$"G{currentRow}:J{currentRow}"].Style.HorizontalAlignment =
                ExcelHorizontalAlignment.Center;
            excelWorksheet.Cells[$"G{currentRow}:J{currentRow}"].Style.Font.Bold = true;
            excelWorksheet.Cells[$"G{currentRow}:J{currentRow}"].Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            excelWorksheet.Row(currentRow).Style.WrapText = true;
            currentRow++;
            excelWorksheet.Row(currentRow).Height = 20.1;
        }

        private void RendertRadarChart(ExcelWorksheet excelWorksheet, int chartStartPosition)
        {
            var radarChart =
                excelWorksheet.Drawings.AddChart("crtExtensionsSize", eChartType.RadarMarkers) as ExcelRadarChart;
            if (radarChart == null)
            {
                return;
            }

            radarChart.SetPosition(chartStartPosition - 3, 0, 7, 0);
            radarChart.SetSize(360, 360);

            var chartEndPosition = chartStartPosition + _checkList.Sections.Count - 1;
            radarChart.Series.Add(
                ExcelCellBase.GetAddress(chartStartPosition, 5, chartEndPosition, 5),
                ExcelCellBase.GetAddress(chartStartPosition, 1, chartEndPosition, 1)
            );

            radarChart.Title.Text = "Сводная оценка";
            radarChart.Title.Font.Size = 14;
            radarChart.Title.Font.Bold = true;

            radarChart.Border.Fill.Style = eFillStyle.NoFill;

            radarChart.DataLabel.ShowLegendKey = false;
            radarChart.DataLabel.ShowValue = false;
            radarChart.DataLabel.ShowCategory = false;
            radarChart.DataLabel.ShowSeriesName = false;
            radarChart.DataLabel.ShowPercent = false;
            radarChart.DataLabel.ShowBubbleSize = false;
            radarChart.DataLabel.ShowLeaderLines = true;

            radarChart.DisplayBlanksAs = eDisplayBlanksAs.Gap;

            radarChart.YAxis.MaxValue = 1.0;
            radarChart.YAxis.MinValue = 0;
            radarChart.YAxis.MajorUnit = 0.25;
            radarChart.YAxis.MajorTickMark = eAxisTickMark.None;
            radarChart.YAxis.MinorTickMark = eAxisTickMark.None;
            radarChart.YAxis.Crosses = eCrosses.AutoZero;
            radarChart.YAxis.CrossBetween = eCrossBetween.Between;
            radarChart.YAxis.CrossesAt = 87114112;

            radarChart.XAxis.Font.Size = 8;
            radarChart.XAxis.Font.Bold = true;

            radarChart.DataLabel.Font.Size = 10;
            radarChart.DataLabel.Font.Bold = true;

            var chartXml = radarChart.ChartXml;
            if (chartXml.DocumentElement != null)
            {
                var nsuri = chartXml.DocumentElement.NamespaceURI;
                var nsm = new XmlNamespaceManager(chartXml.NameTable);
                nsm.AddNamespace("c", nsuri);

                var valAxisNodes = chartXml.SelectNodes("c:chartSpace/c:chart/c:plotArea/c:valAx", nsm);
                if (valAxisNodes != null && valAxisNodes.Count > 0)
                {
                    foreach (XmlNode valAxisNode in valAxisNodes)
                    {
                        var major = valAxisNode.SelectSingleNode("c:majorGridlines", nsm);
                        //Needed to make chart's lines dashed
                        if (major != null)
                        {
                            major.InnerXml =
                                "<c:spPr><a:ln w=\"6350\"><a:solidFill><a:schemeClr val=\"tx1\"><a:lumMod val=\"75000\"/><a:lumOff val=\"25000\"/></a:schemeClr></a:solidFill><a:prstDash val=\"dash\"/></a:ln></c:spPr>";
                        }
                    }
                }
            }

            radarChart.Legend.Remove();
        }

        private void RenderBottomTableSections(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            foreach (var section in _checkList.Sections)
            {
                currentRow++;
                InitBottomTableSectionStyle(excelWorksheet, ref currentRow);
                excelWorksheet.Cells[$"A{currentRow}:D{currentRow}"].Value = section.Name;
            }

            //If Sections.Count less than 7, chart overlaps bottom elements
            if (_checkList.Sections.Count >= 7)
            {
                return;
            }

            for (var i = 7 - _checkList.Sections.Count; i > 0; i--)
            {
                currentRow++;
                InitBottomTableSectionStyle(excelWorksheet, ref currentRow);
            }
        }

        private void InitBottomTableSectionStyle(ExcelWorksheet excelWorksheet, ref int currentRow)
        {
            excelWorksheet.Cells[$"A{currentRow}:F{currentRow}"].StyleName = _totalsSectionStyle.Name;

Audits/Controllers/ChecklistsController.cs
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Audits.Models.Checklists;
using Audits.Models.Database_Manager;
using Audits.Models.Security;
using System.Security.Principal;

namespace Audits.Controllers
{
    [HasPermission(Permission = "ReadChecklist")]
    public class ChecklistsController : Controller
    {
        private readonly DatabaseEntities _db = new DatabaseEntities();
        private readonly WindowsIdentity _identity = WindowsIdentity.GetCurrent();

        public ActionResult Index()
        {
            if (!RoleDepository.HasPermission(_identity, "ReadChecklist"))
            {
                return View("~/Views/Error/Unauthorised.cshtml");
            }
            return View(_db.Checklists.ToList());
        }
        
        public ActionResult Create()
        {
            if (!RoleDepository.HasPermission(_identity, "EditChecklist"))
            {
                return View("~/Views/Error/Unauthorised.cshtml");
            }
            ViewBag.Title = "Создать чек-лист";
            ViewBag.Header = "Создание чек-листа";
            return View(new Checklist());
        }

        [HttpPost]
        [HasPermission(Permission = "EditChecklist")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Checklist checklist)
        {
            if (!ModelState.IsValid)
            {
                return View(checklist);
            }

            ChecklistService.Create(checklist, _db);
            return RedirectToAction("Index");
        }
        [HasPermission(Permission = "EditChecklist")]
        public ActionResult AddSection()
        {
            return Request.IsAjaxRequest() ? PartialView("_AddSection", new Section()) : null;
        }

        [HasPermission(Permission = "EditChecklist")]
        public ActionResult AddParameter(string htmlFieldPrefix = "")
        {
            if (!string.IsNullOrEmpty(htmlFieldPrefix))
            {
                ViewData.TemplateInfo.HtmlFieldPrefix = htmlFieldPrefix;
            }
            return Request.IsAjaxRequest() ? PartialView("_AddParameter", new Parameter()) : null;
        }
        
        public ActionResult Edit(int? id)
        {
            if (!RoleDepository.HasPermission(_identity, "EditChecklist"))
            {
                return View("~/Views/Error/Unauthorised.cshtml");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var checklist = _db.Checklists.Find(id);
            if (checklist == null)
            {
                return HttpNotFound();
            }
            ViewBag.Title = "Редактировать чек-лист";
            ViewBag.Header = "Редактирование чек-листа";
            return View("Create", checklist);
        }

        [HttpPost]
        [HasPermission(Permission = "EditChecklist")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Checklist checklist)
        {
            return !ModelState.IsValid || ChecklistService.Update(checklist, _db) < 0
                ? (ActionResult) View("Create", checklist)
                : RedirectToAction("Index");
        }

        [HttpPost]
        [HasPermission(Permission = "EditChecklist")]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                ChecklistService.Delete(id, _db);
            }
            catch (DbUpdateException)
            {
                ViewData["Message"] = "Невозможно удалить чек-лист, т.к. существуют связанные сущности. "
                    + "Например, аудиты или записи расписания аудитов.";
                return View("~/Views/Error/Index.cshtml");
            }
            return RedirectToAction("Index");
        }

        public ActionResult View(int? id)
        {
            if (!RoleDepository.HasPermission(_identity, "ReadChecklist"))
            {
                return View("~/Views/Error/Unauthorised.cshtml");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var checklist = _db.Checklists.Find(id);
            if (checklist == null)
            {
                return HttpNotFound();
            }
            return View("View", checklist);
        }

        public FileResult Export(int? id)
        {            
            if (id == null)
            {
                return null;
            }

            var checkList = _db.Checklists.Find(id);
            if (checkList == null)
            {
                return null;
            }

            var exportService = new ChecklistExportService(checkList);
            var bytes = exportService.GenerateXlsxReport();

            return File(bytes, "application/vnd.ms-excel", checkList.Name + ".xlsx");
        }        
        public ActionResult GetParameterWhichsCantBeDeleted(int checklistId)
        {
            if (!Request.IsAjaxRequest())
            {
                return null;
            }

            var evaluatedParameters =
                _db.EvaluatedParameters.Where(ep => ep.Parameter.Section.Checklist.ID == checklistId)
                    .Select(ep => ep.ParameterID)
                    .ToList();
            return Content(string.Join(" ", evaluatedParameters));
        }
        
        public bool CanChecklistBeDeleted(int checklistId)
        {
            if (!Request.IsAjaxRequest())
            {
                return false;
            }

            var esCount = _db.EvaluatedSections.Count(es => es.Section.ChecklistID == checklistId);
            var auditsCount = _db.Audits.Count(a => a.ChecklistID == checklistId);

            return esCount <= 0 && auditsCount <= 0;
        }
    }
}

Audits/Views/Checklists/Create.cshtml
@model Checklist

@{
    ViewBag.Title = ViewBag.Header;
}

<div class="checklist-container">
    @using (Html.BeginForm(null, null, FormMethod.Post, new {id = "createCheckListForm"}))
    {
        @Html.AntiForgeryToken()

        <div class="panel panel-default">
            <div class="checklist-title-block">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.LabelFor(model => model.Name, "Название чек-листа: ")
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control checklist-input", placeholder = "Название чек-листа"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>

            <div id="section-container">
                @if (Model == null || Model.Sections == null || Model.Sections.Count == 0)
                {
                    @Html.Partial("_AddSection", new Section())
                }
                else
                {
                    foreach (var section in Model.Sections.OrderBy(s => s.OrdinalNumber))
                    {
                        @Html.Partial("_AddSection", section)
                    }
                }
            </div>
            <div id="add-section" class="btn btn-default">+ Добавить раздел</div>
        </div>
        <button class="btn btn-default" onclick="location.href = '@Url.Action("Index", "Checklists")';return false;">
            Вернуться к списку
        </button>
        <input type="submit" value="Сохранить" id="submit-checklist" class="btn btn-success pull-right"/>
        @Html.HiddenFor(model => model.ID, new {@class = "js-checklist-id-field" })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="@Url.Content("~/Scripts/cusom.js")"></script>
    @Scripts.Render(Url.Content("~/Scripts/bootbox.min.js"))
}

@section Styles
{
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet"/>
}

Audits/Views/Checklists/Index.cshtml
@model IEnumerable<Checklist>

@{
    ViewBag.Title = "Перечень чек-листов";
}

<div class="checklist-create-container">
    @Html.ActionLink("Создать чек-лист", "Create", null, new {@class = "btn btn-success checkList-create"})
</div>

<table class="table table-hover checklist-table table-striped table-bordered">
    <thead>
    <tr>
        <th>Название</th>
        <th class="text-center">Действия</th>
    </tr>
    </thead>
    <tbody id="checklist-table-container">
    @foreach (var item in Model)
    {
        <tr class="js-checklist-index">
            <td class="col-md-11 no-padding">
                <a class="checklist-view" href="@Url.Action("View", "Checklists", new {id = item.ID})" title="Просмотр">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td class="col-md-1 no-padding">
                <div class="checklist-action-container">
                    <a href="@Url.Action("Edit", "Checklists", new {id = item.ID})" class="checklist-edit checklist-action" title="Изменить">
                        <span class="glyphicon glyphicon-edit checklist-glyphicon" aria-hidden="true"></span>
                    </a>
                </div>
                <div class="checklist-action-container">
                    <span class="checklist-remove checklist-action js-remove-checklist" title="Удалить">
                        <span class="glyphicon glyphicon-trash checklist-glyphicon" aria-hidden="true"></span>
                    </span>
                    @Html.Partial("_Delete", item)
                </div>
                <input type="hidden" class="js-checklist-id-field" value="@item.ID"/>
            </td>
        </tr>
    }
    </tbody>

</table>

@section Styles
{
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet"/>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="@Url.Content("~/Scripts/cusom.js")"></script>
    @Scripts.Render(Url.Content("~/Scripts/bootbox.min.js"))
}

Audits/Views/Checklists/View.cshtml
@model Checklist

@{
    ViewBag.Title = "Просмотр чек-листа «" + Model.Name + "»";
}

<div class="checklist-container">
    <div class="panel panel-default">
        <div id="section-container">
            @if (Model != null && Model.Sections != null && Model.Sections.Count != 0)
            {
                foreach (var section in Model.Sections.OrderBy(s => s.OrdinalNumber))
                {
                    @Html.Partial("_ViewSection", section)
                }
            }
        </div>
    </div>
</div>
<div>
    <button class="btn btn-default" onclick="location.href = '@Url.Action("Index", "Checklists")';return false;">
        Вернуться к списку
    </button>
    <button class="btn btn-default pull-right" onclick="location.href = '@Url.Action("Export", "Checklists", new {id = Model.ID})';return false;">
        Экспортировать
    </button>
</div>

@section Styles
{
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet"/>
}

Audits/Views/Checklists/_AddParameter.cshtml
@model Parameter

@{
    var parameterPrefix = ViewData.TemplateInfo.HtmlFieldPrefix;
}

<tr class="js-parameter" data-html-field-prefix="@parameterPrefix">
    @using (Html.BeginCollectionItem(parameterPrefix + ".Parameters"))
    {
        <td class="col-md-6">
            @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control parameter-input"}})
            @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
        </td>
        <td class="col-md-3">
            @Html.EditorFor(model => model.MaxValue, new {htmlAttributes = new {@class = "form-control parameter-input", min = 0}})
            @Html.ValidationMessageFor(model => model.MaxValue, "", new {@class = "text-danger"})
        </td>
        <td class="col-md-3">
            @Html.EditorFor(model => model.SignificanceFactor, new {htmlAttributes = new {@class = "form-control parameter-input", min = 0}})
            @Html.ValidationMessageFor(model => model.SignificanceFactor, "", new {@class = "text-danger"})
        </td>
        <td class="col-md-3 borderless">
            <div class="btn btn-sm btn-default btn-remove js-removing js-remove-parameter remove-parameter">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </div>
        </td>
        <td class="hidden">
            @Html.HiddenFor(model => model.OrdinalNumber, new {@class = "js-parameter-ordinal-number", Value = 1})
            @Html.HiddenFor(model => model.SectionID)
            @Html.HiddenFor(model => model.ID, new {@class = "js-parameter-id-field"})
        </td>
    }
</tr>

Audits/Views/Checklists/_AddSection.cshtml
@model Section

@using (Html.BeginCollectionItem("Sections"))
{
    <div class="panel panel-default js-section">
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="section-title-block">
            <div class="inline-block section-title">
                @Html.LabelFor(model => model.Name, "Имя раздела: ", new {@class = "control-label"})
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control checkList-input", placeholder = "Имя раздела"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
            <div class="inline-block">
                <div class="btn btn-sm btn-default btn-remove js-removing js-remove-section">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    Удалить раздел
                </div>
            </div>
        </div>

        @Html.HiddenFor(model => model.OrdinalNumber, new {@class = "js-section-ordinal-number", Value = 1})
        @Html.HiddenFor(model => model.ChecklistID)
        @Html.HiddenFor(model => model.ID)

        <div class="js-parameters-block">
            <table class="table table-bordered checklist-parameters-table">
                <thead>
                <tr>
                    <th class="col-md-6">Параметры проверки</th>
                    <th class="col-md-3">Макс. оценка</th>
                    <th class="col-md-3">Значимость</th>
                </tr>
                </thead>
                <tbody class="js-parameters-body">
                @if (Model != null && Model.Parameters == null || Model.Parameters.Count == 0)
                {
                    @Html.Partial("_AddParameter", new Parameter())
                }
                else
                {
                    foreach (var parameter in Model.Parameters.OrderBy(m => m.OrdinalNumber))
                    {
                        @Html.Partial("_AddParameter", parameter)
                    }
                }
                </tbody>
            </table>
            <div class="btn btn-default js-add-parameter">+ Добавить параметр</div>
        </div>
    </div>
}

Audits/Views/Checklists/_Delete.cshtml
@model Checklist

@using (Html.BeginForm("Delete", "Checklists", FormMethod.Post, new {@class = "hidden js-checklist-deletion-form"}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(checklist => checklist.ID)
}

Audits/Views/Checklists/_ViewParameter.cshtml
@model Parameter


<tr>
    <td class="col-md-6">
        @Model.Name
    </td>
    <td class="col-md-3">
        @Model.MaxValue
    </td>
    <td class="col-md-3">
        @Model.SignificanceFactor
    </td>
</tr>

Audits/Views/Checklists/_ViewSection.cshtml
@model Section

<div class="panel panel-default js-section">
    <div class="section-title-block">
        @Model.Name
    </div>

    <div class="js-parameters-block">
        <table class="table table-bordered checklist-parameters-table">
            <thead>
            <tr>
                <th class="col-md-3">Параметры проверки</th>
                <th class="col-md-1">Оценка</th>
                <th class="col-md-1">Значимость</th>
            </tr>
            </thead>
            <tbody class="js-parameters-body">
            @if (Model != null && Model.Parameters != null && Model.Parameters.Count != 0)
            {
                foreach (var parameter in Model.Parameters.OrderBy(m => m.OrdinalNumber))
                {
                    @Html.Partial("_ViewParameter", parameter)
                }
            }
            </tbody>
        </table>
    </div>
</div>