Audits/Models/Timetable/TimetableService.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using Audits.Models.Database_Manager;

namespace Audits.Models.Timetable
{
    public class TimetableService
    {
        private readonly HashSet<int> _subdivisionIds;

        public TimetableService(IEnumerable<int> subdivisionIds)
        {
            if (subdivisionIds == null)
            {
                throw new ArgumentNullException(nameof(subdivisionIds));
            }

            _subdivisionIds = new HashSet<int>(subdivisionIds);
        }

        public TimetableRecord[] LoadRecords(int year, int month, int day)
        {
            if (year < 1900 || year > 3000)
            {
                throw new ArgumentOutOfRangeException(nameof(year));
            }
            if (month < 1 || month > 12)
            {
                throw new ArgumentOutOfRangeException(nameof(year));
            }
            if (day < 1 || day > DateTime.DaysInMonth(year, month))
            {
                throw new ArgumentOutOfRangeException(nameof(year));
            }

            using (var db = new DatabaseEntities())
            {
                var records = db
                    .TimetableRecords
                    .Where(x => x.Date.Year == year
                                && x.Date.Month == month
                                && x.Date.Day == day)
                    .Include(x => x.Subdivision)
                    .Include(x => x.Checklist)
                    .ToArray();

                return records
                    .Where(x => _subdivisionIds.Contains(x.SubdivisionID))
                    .ToArray();
            }
        }

        public bool[] DaysWithRecords(int year, int month)
        {
            if (year < 1900 || year > 3000)
            {
                throw new ArgumentOutOfRangeException(nameof(year));
            }
            if (month < 1 || month > 12)
            {
                throw new ArgumentOutOfRangeException(nameof(year));
            }

            var daysInMonth = DateTime.DaysInMonth(year, month);
            var result = new bool[daysInMonth];

            using (var db = new DatabaseEntities())
            {
                var monthlyRecords = db.TimetableRecords
                    .Where(x => x.Date.Year == year && x.Date.Month == month)
                    .ToArray();

                var timetableRecords = monthlyRecords
                    .Where(x => _subdivisionIds.Contains(x.SubdivisionID))
                    .ToArray();

                for (var i = 1; i <= daysInMonth; i++)
                {
                    result[i - 1] = timetableRecords.Any(x => x.Date.Day == i);
                }
            }

            return result;
        }
    }
}

Audits/Controllers/AuditsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Audits.Models.Audits;
using Audits.Models.Database_Manager;
using Audits.Models.Security;
using System.Text.RegularExpressions;
using System.Security.Principal;
using Audits.Models.EmployeesManager;

namespace Audits.Controllers
{
    public class AuditsController : Controller
    {
        private readonly DatabaseEntities _db;
        private readonly WindowsIdentity _identity;

        public AuditsController()
        {
            _db = new DatabaseEntities();
            AuditsService = new AuditsService();
            _identity = WindowsIdentity.GetCurrent();
        }

        private AuditsService AuditsService { get; }

        [HasPermission(Permission = "ReadAudits")]
        public ActionResult Export(int? id, bool mode)
        {
            if (id.HasValue)
            {
                var audit = AuditsService.GetDetails(id);

                if (audit != null)
                {
                    byte[] bytes = null;
                    AuditExportService auditExportService = new AuditExportService(audit);
                    if (mode)
                    {
                        bytes = auditExportService.GenerateXlsxReport();
                    }
                    else
                    {
                        bytes = auditExportService.GenerateXlsxActionsReports();
                    }
                    return File(bytes, "application/vnd.ms-excel", audit.Checklist.Name + ".xlsx");
                }
                return HttpNotFound();
            }
            return View("Error");
        }

        [HasPermission(Permission = "ReadAudits")]
        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                var audit = AuditsService.GetDetails(id);

                if (audit != null)
                {
                    return View(audit);
                }
                return HttpNotFound();
            }
            return View("Error");
        }

        public ActionResult Validate(int? id)
        {
            bool isTrustedAuditor = RoleDepository.HasPermission(WindowsIdentity.GetCurrent(), "ValidateauditTrusted");
            bool isKRPSAuditor = RoleDepository.HasPermission(WindowsIdentity.GetCurrent(), "ValidateauditKrps");

            if (id.HasValue)
            {
                var audit = AuditsService.ValidationPrepare((int)id);
                if (audit != null)
                {
                    if (audit.ValidatedAudit != null && audit.ValidatedAudit.ValidatedAudit == null && isKRPSAuditor)
                    {
                        //Accept prove already proven by trusted auditor audit
                        return View(AuditsService.ValidationPrepare((int)audit.ValidatedAuditID));
                    }
                    else if (audit.ValidatedAudit == null && isTrustedAuditor)
                    {
                        //Accept prove audit by trusted auditor
                        return View(audit);
                    }
                    //If user has not permission or audit already was proven by KRPS auditor the result "Error"
                    return View("Error");
                }
                return HttpNotFound();
            }
            //here need view that audit is already validated
            return View("Error");
        }

        [HttpPost]
        public ActionResult Validate(string response)
        {
            bool isTrustedAuditor = RoleDepository.HasPermission(WindowsIdentity.GetCurrent(), "ValidateauditTrusted");
            bool isKRPSAuditor = RoleDepository.HasPermission(WindowsIdentity.GetCurrent(), "ValidateauditKrps");

            if (isTrustedAuditor || isKRPSAuditor)
            {
                var result = false;
                var values = new JavaScriptSerializer().Deserialize<AuditValidate>(response);

                int auditId;
                int.TryParse(RouteData.Values["id"].ToString(), out auditId);

                Audit audit = AuditsService.GetDetails(auditId);
                if (audit.ValidatedAudit != null)
                {
                    result = AuditsService.Validate(audit.ValidatedAudit, values);
                }
                else
                {
                    result = AuditsService.Validate(audit, values);
                }

                if (result)
                {
                    return Json(new { success = true, url = Url.Action("Details", new { id = auditId }) });
                }
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }


        // GET: Audit/Index
        // Main page. Lists all available Audits in the database supporting the sort by different keys and batch delete.
        [HasPermission(Permission = "ReadAudits")]
        [HttpGet]
        public ActionResult Index(int id = 1, int range = 1, string sort = "")
        {
            AuditsService.LoadAudits(id, sort, range, HttpContext.GetUserAdId(), _identity);

            // if no audits found
            if (AuditsService.Model == null)
            {
                ViewBag.ErrorName = "Данные не найдены";
                ViewBag.ErrorReason = "AuditsManager/Index не смог выгрузить необходимые данные.";
                return View("Error", null);
            }

            return View(AuditsService);
        }

        // POST: Audit/Index
        // Dispatch delete/edit actions on selected Audit items at Index page.
        [HttpPost]
        [ActionName("Index")]
        [HasPermission(Permission = "WriteAudits")]
        [ValidateAntiForgeryToken]
        public ActionResult Index()
        {
            var postKeys = Request.Form.AllKeys; // get all keys from POST data

            // if Delete button is pressed
            if (postKeys.Contains("action_delete"))
                return IndexDeleteItems();

            // if Edit button is pressed
            if (postKeys.Contains("action_edit"))
            {
                foreach (string key in Request.Form) // just get first available number
                {
                    int val;
                    if (int.TryParse(key, out val))
                    {
                        return RedirectToAction("Edit", new { id = val });
                    }
                }
            }

            // try to find if [x] button is pressed along the entry row
            foreach (var key in postKeys)
            {
                if (Regex.IsMatch(key, "^delete_[0-9]+$"))
                {
                    string[] split = key.Split(new char[] { '_' });
                    int id = 0;
                    if (split.Length != 2)
                        break;
                    // try parse delete_<id>
                    if (!int.TryParse(split.ElementAt(1), out id))
                        break;
                    return Delete(id);
                }
            }

            // if no action was found
            ViewBag.ErrorName = "Неверный запрос";
            ViewBag.ErrorReason = "Не удалось найти выбранное вами действие.";
            return View("Error");
        }

        // Aggregate list of Audit IDs from POST data, iterate and delete all of them 
        [NonAction]
        public ActionResult IndexDeleteItems()
        {
            // parse list of <input checkbox name="<id>" />
            var itemsToDelete = new List<int>();
            foreach (string key in Request.Form)
            {
                int val;
                if (int.TryParse(key, out val))
                {
                    itemsToDelete.Add(val);
                }
            }

            // iterate over itemsToDelete, commit deletion on each cycle
            var i = 0;
            foreach (var id in itemsToDelete)
            {
                if (!AuditsService.DeleteById(id))
                {
                    ViewBag.ErrorName = "Ошибка удаления";
                    ViewBag.ErrorReason = $"Не удалось удалить выбранные записи частично/полностю. Удалены первые {i} записей из [{string.Join(", ", itemsToDelete.ToArray())}].";
                    return View("Error");
                }
                i++;
            }

            return Request.UrlReferrer != null ? Redirect(Request.UrlReferrer.ToString()) : Redirect("Audits/Index");
        }

        // POST: Audit/Delete/5
        // Delete Audit by `id`.
        [HttpPost]
        [HasPermission(Permission = "WriteAudits")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (!AuditsService.DeleteById(id))
            {
                ViewBag.ErrorName = "Ошибка удаления";
                ViewBag.ErrorReason = $"Не удалось удалить выбранную запись из базы данных.";
                return View("Error");
            }

            return RedirectToAction("Index");
        }

        // GET: Audit/Create
        //[HasPermission(Permission = "WriteAudits")]
        [HttpGet]
        public ActionResult Create()
        {
            var currUser = AuditsService.GetUserDetails(_identity);
            if (currUser == null)
            {
                ViewBag.ErrorName = "Пользователь не найден";
                ViewBag.ErrorReason = "Не удалось распознать текущего пользователя.";
                return View("Error");
            }
            return ViewAudit(new Audit() { AuthorID = currUser.ID, Auditor = currUser, IsEditable = true, InputDate = DateTime.Now, Date = DateTime.Now });
        }

        // POST: Audit/Create
        // Creates new Audit by binding the model with POST data.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [HasPermission(Permission = "WriteAudits")]
        public ActionResult Create(Audit audit)
        {
            // check if current user exists in DB
            var currUser = AuditsService.GetUserDetails(_identity);

Audits/Views/Timetable/Create.cshtml
@model TimetableRecord

@{
    ViewBag.Title = "Создать запись расписания";
}

<h2>Создать запись расписания</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Date, "Дата проведения", new {@class = "control-label col-md-2"})
            <div class="col-md-10 ">
                <div class="input-group" id="inputDate">
                    @Html.TextBoxFor(model => model.Date, "{0:yyyy-MM-dd}",
                        new Dictionary<string, object> {{"class", "form-control"}, {"placeholder", "Выберите дату"}, {"data-input", null}})
                    @Html.ValidationMessageFor(model => model.Date, "", new {@class = "text-danger"})
                    <div class="input-group-addon" data-clear>
                        <span class="glyphicon glyphicon-remove"></span>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChecklistID, "Чек-лист", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("ChecklistID", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ChecklistID, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubdivisionID, "Подразделение", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("SubdivisionID", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.SubdivisionID, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К расписанию", "Index")
</div>
@section styles {
    @Styles.Render("~/Content/styles/flatpickr.min.css")
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/flatpickr.js")
    @Scripts.Render("~/Scripts/flatpickr_ru.js")
    <script>
        $(function() {
            //Calendar initalize
            flatpickr("#inputDate",
                {
                    enableTime: false,
                    allowInput: true,
                    locale: 'ru',
                    minDate: 'today',
                    wrap: true,
                    defaultDate: 'today'
                });
        });
    </script>
}

Audits/Views/Timetable/Delete.cshtml
@model TimetableRecord

@{
    ViewBag.Title = "Удалить запись расписания";
}

<h2>Вы уверены, что хотите удалить запись расписания?</h2>

<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>Дата проведения</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd >

        <dt>Чек-лист</dt>
        <dd>@Html.DisplayFor(model => model.Checklist.Name)</dd>

        <dt>Подразделение</dt>
        @if (string.IsNullOrEmpty(Model.Subdivision.SAP_ID))
        {
            <dd>@Html.DisplayFor(model => model.Subdivision.Name)</dd>
        }
        else
        {
            <dd>@Html.DisplayFor(model => model.Subdivision.SAP_ID) : @Html.DisplayFor(model => model.Subdivision.Name)</dd>
        }
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default"/> |
            @Html.ActionLink("К расписанию", "Index")
        </div>
    }
</div>

Audits/Views/Timetable/Details.cshtml
@model TimetableRecord

@{
    ViewBag.Title = "Подробности записи расписания";
}

<h2>Подробности записи расписания</h2>
<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>Дата проведения</dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>Чек-лист</dt>
        <dd>
            @Html.DisplayFor(model => model.Checklist.Name)
        </dd>

        <dt>Подразделение</dt>
        <dd>
            @Html.DisplayFor(model => model.Subdivision.Name)
        </dd>
    </dl>
    @if (Model.Audit.Any())
    {
        <h4>Проведённый аудит:</h4>
        foreach (var item in Model.Audit)
        {
            <dl class="dl-horizontal">
                <dt>Дата проведения</dt>
                <dd>
                    @Html.DisplayFor(x => item.Date)
                </dd>
                <dt>Аудитор</dt>
                <dd>
                    @Html.DisplayFor(x => item.Auditor.LastName)
                    @Html.DisplayFor(x => item.Auditor.FirstName)
                    @Html.DisplayFor(x => item.Auditor.Patronymic)
                </dd>
                <dt>Сопровождающие</dt>
                <dd>
                    @Html.DisplayFor(x => item.Attendees)
                </dd>
                <dt></dt>
                <dd>
                    <a href="@Url.Action("Create", "Audits")">Перейти</a>
                </dd>
            </dl>
        }
    }
    else
    {
        <p>Нет проведённых аудитов.</p>
    }
</div>
<p>
    <a class="btn btn-default" href="@Url.Action("CreateFromTimetable", "Audits", new { checklistId = Model.ChecklistID, subdivisionID = Model.SubdivisionID, dateStr = Model.Date.ToString("yyyy-MM-dd") })">Провести &raquo;</a> |
    @Html.ActionLink("Редактировать", "Edit", new {id = Model.ID}) |
    @Html.ActionLink("К расписанию", "Index")
</p>
@section styles {
    @Styles.Render("~/Content/monthly.css")
}

Audits/Views/Timetable/Edit.cshtml
@model TimetableRecord

@{
    ViewBag.Title = "Редактировать запись расписания";
}

<h2>Редактировать запись расписания</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            <label class="control-label col-md-2">Дата проведения</label>
            <div class="col-md-10 ">
                <div class="input-group" id="inputDate">
                    @Html.TextBoxFor(model => model.Date, "{0:yyyy-MM-dd}",
                        new Dictionary<string, object> {{"class", "form-control"}, {"placeholder", "Выберите дату"}, {"data-input", null}})
                    @Html.ValidationMessageFor(model => model.Date, "", new {@class = "text-danger"})
                    <div class="input-group-addon" data-clear>
                        <span class="glyphicon glyphicon-remove"></span>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Чек-лист</label>
            <div class="col-md-10">
                @Html.DropDownList("ChecklistID", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ChecklistID, "", new {@class = "text-danger"})
            </div>
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <label class="control-label col-md-2">Подразделение</label>
            <div class="col-md-10">
                @Html.DropDownList("SubdivisionID", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.SubdivisionID, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К расписанию", "Index")
</div>
@section styles {
    @Styles.Render("~/Content/styles/flatpickr.min.css")
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/flatpickr.js")
    @Scripts.Render("~/Scripts/flatpickr_ru.js")
    <script>
        $(function() {
            //Calendar initalize
            flatpickr("#inputDate",
                {
                    enableTime: false,
                    allowInput: true,
                    locale: 'ru',
                    minDate: 'today',
                    wrap: true,
                    defaultDate: '@Model.Date.ToString("yyyy-MM-dd")'
                });
        });
    </script>
}

Audits/Views/Timetable/Index.cshtml
@model IEnumerable<TimetableRecord>
@{
    ViewBag.Title = "Расписание Аудитов";
}
<h2>Расписание</h2>
<hr/>
<div class="row">
    <div class="col-lg-offset-3 col-md-6" id="mycalendar"></div>
</div>

<div class="row">
    @using (Ajax.BeginForm("Details", null,
        new AjaxOptions
        {
            HttpMethod = "get",
            InsertionMode = InsertionMode.ReplaceWith,
            UpdateTargetId = "partial-timetable"
        }, new {method = "GET", style = "display: none;"}))
    {
        <input type="hidden" id="year" name="year" value=""/>
        <input type="hidden" id="month" name="month" value=""/>
        <input type="hidden" id="day" name="day" value=""/>
        <input id="btn-submit" type="submit"/>
    }
</div>

<hr />
<h4>Перечень аудитов:</h4>
@Html.Partial("PartialViews/ListOfScheduledAudits", Model)
@section styles {
    @Styles.Render("~/Content/monthly.css")
}
@section scripts {
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/Scripts/monthly.js")
    <script type="text/javascript">
        var dayValues = [];

        function loadDayValues(year, month) {
            $.get('@Url.Action("GetDayValues")/?year=' + year + '&month=' + month,
                function (data) {
                    dayValues = data;
                    setDayValues(year, month);
                });
        }

        function setDayValues(year, month) {
            for (var i = 0; i < dayValues.length; ++i) {
                if (dayValues[i]) {
                    var date = new Date(year, month - 1, i);
                    changeCellColor(date, '#C1A2E3');
                }
            }
        }

        function changeCellColor(date, color) {
            var classSelector = '.dt' +
                ('0' + date.getFullYear()).slice(-4) +
                '-' +
                ('0' + (date.getMonth() + 1)).slice(-2) +
                '-' +
                ('0' + date.getDate()).slice(-2);
            var cell = $(classSelector);
            cell.css('background-color', color);
        }

        $(function() {
            $('#mycalendar').monthly({
                weekStart: 'Mon',
                mode: 'event',
                dataType: 'json',
                eventList: 'true',
                onSetNextMonth: function () {
                    console.log('next');
                    var month = $('#mycalendar').data("setMonth");
                    var year = $('#mycalendar').data("setYear");
                    $('#day').val(null);
                    $('#btn-submit').click();
                    loadDayValues(year, month);
                },
                onSetPrevMonth: function () {
                    console.log('prev');
                    var month = $('#mycalendar').data("setMonth");
                    var year = $('#mycalendar').data("setYear");
                    $('#day').val(null);
                    $('#btn-submit').click();
                    loadDayValues(year, month);
                }
            });
            // Detach default click handler
            $(document.body).off('click touchstart', '#mycalendar .monthly-day', null);
            // Attach our own click handler
            $(document.body).on('click touchstart',
                '#mycalendar .monthly-day',
                function() {
                    var day = $(this).data("number");
                    var month = $('#mycalendar').data("setMonth");
                    var year = $('#mycalendar').data("setYear");

                    var date = new Date(year, month - 1, day);
                    date.setDate(date.getDate() - 1);

                    $('.monthly-day').css('background-color', '#FFFFFF');
                    setDayValues(year, month);
                    changeCellColor(date, '#A1C2E3');

                    $('#day').val(day);
                    $('#month').val(month);
                    $('#year').val(year);

                    $('#btn-submit').click();
                });

            var dateToday = new Date();
            loadDayValues(dateToday.getFullYear(), dateToday.getMonth() + 1);
        });
    </script>
}